name: identificacion
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img1.jpg
  
  fonts:
    - family: ELEGANT TYPEWRITER
      fonts:
        - asset: assets/fonts/ELEGANT TYPEWRITER Bold.ttf
        - asset: assets/fonts/ELEGANT TYPEWRITER Light.ttf
        - asset: assets/fonts/ELEGANT TYPEWRITER Regular.ttf
